### ISSUE TITLE
[활동등록] 상단 gnb 로고가 깨집니다.

### ISSUE THREAD

**Issue by duoh20** [byulmee/byulmee#15]
**이슈 화면:**
<img width="795" alt="스크린샷 2021-01-25 오후 5 04 35" src="https://user-images.githubusercontent.com/59134456/105677597-69ea5a80-5f2f-11eb-90b1-42edb3d54e2a.png">

**경로:**
작업실 > 활동 등록

**이슈:**
gnb의 로고 이미지가 깨져서 보입니다.

**테스트 환경:**
chrome 87.0.4280.88, Mac OS(Catalina 10.15.5)

**Comment by SangYoungBaek** [comment]
activityInsert/activityUpdate/productInsert/productUpdate.jsp 에서
![KakaoTalk_20210125_213401627](https://user-images.githubusercontent.com/47877063/105707554-77ffa180-5f56-11eb-94a4-3bbee6495ad5.png)
![KakaoTalk_20210125_213604158](https://user-images.githubusercontent.com/47877063/105707563-7afa9200-5f56-11eb-9566-78faf54aab85.png)
이렇게 변경하시면 해결됩니다
