### ISSUE TITLE
[작업실]특정 메뉴를 클릭하면 유저 프로필이 사라집니다.

### ISSUE THREAD

**Issue by duoh20** [byulmee/byulmee#20]
**화면:**
<img width="982" alt="스크린샷 2021-01-25 오후 8 08 17" src="https://user-images.githubusercontent.com/59134456/105698412-30bee400-5f49-11eb-9180-107eb5c36594.png">
<img width="1038" alt="스크린샷 2021-01-25 오후 8 08 11" src="https://user-images.githubusercontent.com/59134456/105698425-34526b00-5f49-11eb-9383-fd3df72592be.png">

**경로:**
작업실>주문 내역 관리
작업실>고객 문의 관리

**이슈:**
- 해당 목록을 클릭하면 프로필이 사라집니다.

**테스트 환경:**
chrome 87.0.4280.88, Mac OS(Catalina 10.15.5)

**Comment by SangYoungBaek** [comment]
src 의 주소를 

${ pageContext.servletContext.contextPath }/resources/images/board/이미지파일명 변경시 해결
